version: "3"
services:
  zoo-1:
    image: zookeeper
    container_name: zoo-1
    hostname: zookeeper
    ports:
      - "2181:2181"
      # - "2888:2888"
      # - "3888:3888"
      # - "8080:8080"
    environment: 
      ZOO_MY_ID: 11
      ZOO_SERVERS: server.11=zoo-1:2888:3888;2181 server.12=zoo-2:2888:3888;2181 server.13=zoo-3:2888:3888;2181
      ZOO_LOG4J_PROP: "INFO,ROLLINGFILE"
    # volumes: 
      # 挂载配置文件
      # - "./master-slave/zoo-1/conf/zoo.cfg:/conf/zoo.cfg"
      # 挂载数据卷
      # - "./master-slave/zoo-1/data/myid:/data/myid"
      # 挂载日志卷
      # - "./master-slave/zoo-1/logs:/datalog"
    networks: 
      - zk
  zoo-2:
    image: zookeeper
    container_name: zoo-2
    hostname: zoo-2
    ports:
      - "2182:2181"
      # - "2889:2888"
      # - "3889:3888"
      # - "8081:8080"
    environment: 
      ZOO_MY_ID: 12
      ZOO_SERVERS: server.11=zoo-1:2888:3888;2181 server.12=zoo-2:2888:3888;2181 server.13=zoo-3:2888:3888;2181
      ZOO_LOG4J_PROP: "INFO,ROLLINGFILE"
    # volumes: 
      # 挂载配置文件
      # - "./master-slave/zoo-2/conf/zoo.cfg:/conf/zoo.cfg"
      # 挂载数据卷
      # - "./master-slave/zoo-2/data/myid:/data/myid"
      # 挂载日志卷
      # - "./master-slave/zoo-2/logs:/datalog"
    networks: 
      - zk
  zoo-3:
    image: zookeeper
    container_name: zoo-3
    hostname: zoo-3
    ports:
      - "2183:2181"
      # - "2889:2888"
      # - "3889:3888"
      # - "8081:8080"
    environment: 
      ZOO_MY_ID: 13
      ZOO_SERVERS: server.11=zoo-1:2888:3888;2181 server.12=zoo-2:2888:3888;2181 server.13=zoo-3:2888:3888;2181
      ZOO_LOG4J_PROP: "INFO,ROLLINGFILE"
    # volumes: 
      # 挂载配置文件
      # - "./master-slave/zoo-3/conf/zoo.cfg:/conf/zoo.cfg"
      # 挂载数据卷
      # - "./master-slave/zoo-3/data/myid:/data/myid"
      # 挂载日志卷
      # - "./master-slave/zoo-3/logs:/datalog"
    networks: 
      - zk
networks:
  zk: