version: "3"
services:
  zoo-standalone:
    image: zookeeper
    container_name: zoo-standalone
    hostname: zookeeper
    ports:
      - "2181:2181"
      # - "2888:2888"
      # - "3888:3888"
      # - "8080:8080"
    environment: 
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo-1:2888:3888;2181
      ZOO_LOG4J_PROP: "INFO,ROLLINGFILE"
    # volumes: 
      # 挂载配置文件
      # - "./master-slave/zoo-1/conf/zoo.cfg:/conf/zoo.cfg"
      # 挂载数据卷
      # - "./master-slave/zoo-1/data/myid:/data/myid"
      # 挂载日志卷
      # - "./master-slave/zoo-1/logs:/datalog"
    networks: 
      - zk-standalone
networks:
  zk-standalone: