version: "3"
services:
  mysql-standalone:
      image: mysql:5.7
      container_name: mysql-standalone
      hostname: mysql-5.7
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: 123456
      volumes:
        - "./single/data:/var/lib/mysql"
        - "./single/conf:/etc/mysql/conf.d"
        - "./single/logs:/var/log/mysql"
      # restart: always
      networks:
        - db
networks:
  db: