version: "3"
services:
  mysql-master:
      image: mysql:5.7
      container_name: mysql-master
      hostname: mysql-5.7
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: 123456
      volumes:
        - "./master-slave/master/data:/var/lib/mysql"
        - "./master-slave/master/conf:/etc/mysql/conf.d"
        - "./master-slave/master/logs:/var/log/mysql"
      # restart: always
      networks:
        - db
  mysql-slave-1:
      image: mysql:5.7
      container_name: mysql-slave-1
      hostname: mysql-5.7
      ports:
        - "3316:3306"
      environment:
        MYSQL_ROOT_PASSWORD: 123456
      volumes:
        - "./master-slave/slave-1/data:/var/lib/mysql"
        - "./master-slave/slave-1/conf:/etc/mysql/conf.d"
        - "./master-slave/slave-1/logs:/var/log/mysql"
      # restart: always
      networks:
        - db
  mysql-slave-2:
      image: mysql:5.7
      container_name: mysql-slave-2
      hostname: mysql-5.7
      ports:
        - "3326:3306"
      environment:
        MYSQL_ROOT_PASSWORD: 123456
      volumes:
        - "./master-slave/slave-2/data:/var/lib/mysql"
        - "./master-slave/slave-2/conf:/etc/mysql/conf.d"
        - "./master-slave/slave-2/logs:/var/log/mysql"
      # restart: always
      networks:
        - db
networks:
  db: