version: '3'
services:
  mongo:
    image: mongo
    container_name: mongodb
    hostname: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USENAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      - db
networks:
  db: